level = [
"WWWWWWWWWWWWWWWWWWWW",
"W                  W",
"W         WWWWWW   W",
"W   WWWW       W   W",
"W   W        WWWW  W",
"W WWW  WWWW        W",
"W   W              W",
"W   W         W W  W",
"W   WWW WWW   W W  W",
"W     W   W   W W  W",
"WWW   W   WWWWW W  W",
"W         W        W",
"W  W  WWWWW   WWW  W",
"W  W  W        W   W",
"WWWWWWWWWWWWWWWWWWWW",
]
