'''
O = empty tile, usually used for spawn point of ghosts.
W = wall
'''

level = [
"WWWWWWWWWWWWWWWWWWWW",
"W                  W",
"W         WWWWWW   W",
"W   WWWW       W   W",
"W   W        WWWW  W",
"W WWW  WWWW        W",
"W   W              W",
"W   W         W W  W",
"W   WWW WWW   W W  W",
"W     W   W   W W  W",
"WWW   W   WWWWW W  W",
"W         W        W",
"W  W  WWWWW   WWW  W",
"W  W  W        W   W",
"WWWWWWWWWWWWWWWWWWWW",
]

level1 = [
"WWWWWWWWWWWWWWWWWWWW",
"WIIIIIIWOOOOWIIIIIIW",
"WIIIIIIWOOOOWIIIIIIW",
"WIWWIIIWWOOWWIIIWWIW",
"WIWIIIIIIIIIIIIIIWIW",
"WIWIIWIIIIIIIIWIIWIW",
"WIWWIWIWWWWWWIWIWWIW",
"WIIIIIIIIIIIIIIIIIIW",
"WWWWWWWWWWWWWWWWWWWW",
]

level2 = [
"WWWWWWWWWWWWWWWWWWWW",
"W IIII WOOOOW IIII W",
"WIIIIIIWOOOOWIIIIIIW",
"W WWIIIWWOOWWIIIWW W",
"W W IIIIIIIIIIII W W",
"W W IWIIIIIIIIWI W W",
"W WW W WWWWWW W WW W",
"W   I I      I I   W",
"WWWWWWWWWWWWWWWWWWWW",
]
level4 = [
"WWWWWWWWWWWWWWWWWWWW",
"WIIIIIIWOOOOWIIIIIIW",
"W WWIIIWWOOWWIIIWW W",
"W W IWIIIIIIIIWI W W",
"W WW W WWWWWW W WW W",
"WI  I I      I I  IW",
"WWWWWWWWWWWWWWWWWWWW",
]

#Not done
level3 = [
"WWWWWWWWWWWWWWWWWWW",
"WI  I   IWI   I  IW",
"W WW WWW W WWW WW W",
"WI  I I I I I I  IW",
"W "
]
